# (PART\*) Theory {-} 

# Likelihood {#Theory}

Part II provides background on the theory of SECR that is mostly for reference. These chapters aim to be independent of any particular implementation, although some cross-references to **secr** creep in. The notation and terminology originated in @be08, with extensions from @ebb09, @e11 and elsewhere. 

## Notation
\index{Notation}

| Category | Symbol |  Meaning           |
|:---|:----|:----------------------------|
| General ||
|| AC         | activity centre |
|| $\vec x$   | point $(x,y)$ in the plane |
| Data ||
|| $n$        | number of individuals detected |
|| $S$        | number of sampling occasions |
|| $K$        | number of detectors |
|| $\omega_i$ | spatial detection history of the $i$-th animal |
|| $\Omega$   | set of all detection histories $\omega_i, i = 1..n$ |
| Parameters  ||
|| $D(\vec x; \phi)$[^footnote4a] | intensity at $\vec x$ of AC Poisson point process  |
|| $\phi$     | parameter vector for AC point process (scalar density if surface flat) |
|| $\theta$   | vector of detection parameters (minimally $(g_0, \sigma)$ or $(\lambda_0,\sigma)$)|
|| $g_0$      | intercept of distance-probability-of-detection function |   
|| $\lambda_0$ | intercept of distance-hazard-of-detection function |   
|| $\sigma$   | spatial scale parameter of distance-detection function |   
| Model ||
|| $d_k(\vec x)$ | distance of point $\vec x$ from detector $k$ |
|| $\lambda(d)$  | hazard of detection at distance $d$ (distance-hazard-of-detection function) |
|| $g(d)$  | probability of detection at distance $d$ (distance-probability-of-detection function)|
|| $p_\cdot(\vec x; \theta)$ | probability that an individual with AC at $\vec x$ is detected at least once |
|| $h_{isk}(\vec x; \theta)$ | hazard of detection at detector $k$ for animal $i$ on occasion $s$ |
|| $p_{isk}(\vec x; \theta)$ | probability of detection corresponding to $h_{isk}(\vec x; \theta)$|
|| $p_{k}(\vec x; \theta)$ | $p_{isk}(\vec x; \theta)$ constant across individuals $i$ and occasions $s$|
| Habitat ||
|| $A$        | potential habitat ('habitat mask', 'state space') $A \subset R^2$ |
|| $|A|$      | area of $A$ |
|| $N(A)$     | number of AC in $A$ |

[^footnote4a]: We use $D(\vec x)$ in preference to $\lambda(\vec x)$ because $\lambda$ has multiple meanings.

## Likelihood {#Likelihood}
\index{Likelihood!SECR}

This formulation of the likelihood is based on @be08 with minor changes in notation:
\begin{equation}
L(\phi, \theta | \Omega ) = \mbox{Pr}(n| \phi, \theta) \; \mbox{Pr}(\Omega | n, \phi, \theta).
(\#eq:L)
\end{equation}

Parameters of the state model ($\phi$) and the detection model ($\theta$) are estimated jointly by maximizing the logarithm of the likelihood. When density is constant across space, $\phi$ drops out of the rightmost term, which then relates to the detection (observation) model alone, and maximization of this component gives unbiased estimates of $\theta$ (see [Conditional likelihood](#conditional)).

### Number of individuals {#Pr-n}
\index{Poisson process (2-D)}
\index{Activity centres}
If AC follow an inhomogeneous Poisson process then $n$ has a Poisson distribution with parameter 
\begin{equation}
\lambda = \int_{R^2} D(\vec x; \phi) \, p_\cdot(\vec x;\theta) \, d\vec x, 
(\#eq:n)
\end{equation}
where $D(\vec x; \phi)$ is the density at $\vec x$ and $p_\cdot(\vec x|\theta)$ is the overall probability of detecting an AC at $\vec x$ (see Sections \@ref(pointdetectors) and \@ref(areasearches)). Thus $\mbox{Pr}(n | \phi, \theta) = \lambda^n \exp (-\lambda) / n!$. The distribution of $n$ is binomial when the population size in a defined area is [fixed](#fixedN).

### Detection histories {#Pr-omega}

In general we have
\begin{equation}
\mbox{Pr} (\Omega | n, \phi, \theta) = \binom {n}{n_1,...,n_C}
\prod_{i=1}^n \mbox{Pr}( \omega_i | \omega_i>0, \phi, \theta),
 (\#eq:CL)
\end{equation}

where $\omega_i>0$ indicates a non-empty detection history. The multinomial coefficient uses the frequencies $n_1,...,n_C$ of each of the $C$ observed histories. The coefficient is a constant not involving parameters and it can be omitted without changing the model fit (consistent inclusion or exclusion is needed for valid likelihood-based comparisons such as those using AIC).

We do not know the true AC locations, but they can be integrated[^integration] out of the likelihood using an expression for their spatial distribution, i.e.
\begin{equation}
\mbox{Pr}( \omega_i | \omega_i>0, \phi, \theta) = \int_{R^2} \mbox{Pr}( \omega_i | \omega_i>0, \theta, \vec x) \, f(\vec x | \omega_i>0, \phi, \theta) \; d\vec x
(\#eq:omegai)
\end{equation}
where $f(\vec x| \omega_i>0, \phi, \theta)$ is the conditional density of an AC given that the individual was detected. The conditional density is given by
\begin{equation}
f(\vec x| \omega_i>0, \phi, \theta) = \frac{D(\vec x ; \phi) p_\cdot(\vec x ; \theta)}{\lambda(\phi,\theta)}.
(\#eq:f)
\end{equation}

[^integration]: Integration is commonly performed by summing over many small cells for a finite region near the detectors, as both $\mbox{Pr}(\omega_i)$ and $f(\vec x)$ decline to zero at greater distances. We state the model in terms of the real plane and defer discussion of the region of integration to Chapter \@ref(Habitat).

## Distance-dependent detection

\index{Detection model!functions}

The key idea of SECR is that the probability of detecting a particular animal at a particular detector on one occasion can be represented as a function of the distance between its AC and the detector. The function should decline effectively to zero at large distances. Distances are not observed directly, and we rely on functions of somewhat arbitrary shape. Fortunately, the estimates are not very sensitive to the choice. Detection functions are covered in detail in Chapter \@ref(Detection). Either probability $g(d)$ or hazard $\lambda(d)$ may be modelled as a function of distance. A halfnormal form is commonly used (e.g., $g(d) = g_0 \exp (-d^2/2/\sigma^2)$). The shapes of, e.g., halfnormal $g(d)$ and halfnormal $\lambda_0(d)$ are only subtly different, but $\lambda(d)$ is preferred because it lends itself to mathematical manipulation and occurs more widely in the literature (often with different notation).

The function $\lambda(d)$ may be transformed into a probability with $g(d) = 1 - \exp[-\lambda(d)]$ and the reverse transformation is $\lambda(d) = -\log[1-g(d)]$. The intercept parameter $g_0$ has been replaced by $\lambda_0$; although the name $\sigma$ is retained for the spatial scale parameter this is not exactly interchangeable between the models.

## Detector types  {#pointdetectors}
\index{Detectors}

The SECR data $\omega_i$ for each detected individual comprise a matrix with dimensions $S$ (occasions) and $K$ (detectors). Each element may be binary (0/1) or integer (0, 1, 2, ...). Various probability models exist for the entries $\omega_{isk}$. The appropriate probability model follows in most cases directly from the type of detector device; we therefore classify probability models according to device type. Table \@ref(tab:detectortypes) matches this classification to that of @rcsg14. This section covers passive detection at a point; [area searches](#areasearches) are considered later.


Table: (\#tab:detectortypes) Detector types (based on @eb19[Table 1])

| Detector type | @rcsg14 | Data |
|:-----------------|:------------|:---------------------------|
| Binary proximity | Bernoulli^1^ | binary animal $\times$ occasion $\times$  detector|
| Poisson count proximity | Poisson | integer animal $\times$ occasion $\times$  detector |
| Binomial count proximity | Binomial | integer animal $\times$ occasion $\times$  detector |
| Multi-catch trap | Multinomial | binary animal $\times$ occasion |
| Single-catch trap | --- | binary animal $\times$ occasion, exclusive |
| Area search || integer animal $\times$ occasion $\times$  detector |
| Transect search || integer animal $\times$ occasion $\times$  detector |
| Exclusive area search^2^ || binary animal $\times$ occasion |
| Exclusive transect search^2^ || binary animal $\times$ occasion |

1. Also 'Binomial' in @rg11
2. 'Exclusive' here means that an individual can be detected at no more than one detector (polygon or transect) per occasion.

For each type of detector we require $\mbox{Pr}(\omega_{isk} | \vec x)$ and the overall probability of detection $p_\cdot(\vec x)$. For some detector types it is more natural to express the probability in terms of the occasion- and trap-specific hazard $h_{sk} = \lambda[d_k(\vec x); \theta^\prime]  = -\log(1-g[d_k(\vec x); \theta])$ than the probability $p_{sk} (\vec x) = g[d_k(\vec x); \theta] = 1 - \exp\{-\lambda[d_k(\vec x); \theta^\prime]\}$[^footnote4b].

We summarise the probability models in Table \@ref(tab:pointdetectortypes), with comments on each point detector type below.

Table: (\#tab:pointdetectortypes) Summary of point detector types (conditioning on $\theta$ omitted to save space)

| Detector type | $\mbox{Pr}(\omega_{isk} | \vec x)$ | $p_\cdot(\vec x)$ | 
|:-----------------|:-------------------|:-------------------|
| Binary proximity | $p_{sk}(\vec x) ^{\omega_{isk}} [1-p_{sk}(\vec x)]^{(1-\omega_{isk})}$ | $1 - \prod_s\prod_k 1 - p_{sk} (\vec x)$|
| Poisson count proximity | $\{h_{sk} (\vec x)^{\omega_{isk}} \exp [-h_{sk}(\vec x)]\} / \omega_{isk}!$ | $1 - \exp [- \sum_s \sum_k h_{sk}(\vec x)]$|
| Binomial count proximity^1^ | $\binom{B_s}{\omega_{isk}} p_{sk}(\vec x)^{\omega_{isk}} [1-p_{sk}(\vec x)]^{(B_s-\omega_{isk})}$ |  $1 - \prod_s\prod_k [1 - p_{sk} (\vec x)]^{B_s}$ | 
| Multi-catch trap^2^ | $\{1 - \exp [-H_s(\vec x)]\}\frac{h_{sk}(\vec x)}{H_s(\vec x)}$ | $1 - \exp[ -\sum_s H_s(\vec x)]$|

1. $B_s$ is the size of the binomial distribution, the number of opportunities for detection, assumed constant across detectors 
2. $H_s = \sum_k h_{sk}(\vec x)$ is the hazard summed over traps  

### Binary proximity detector
\index{Detectors!binary proximity}

A proximity detector records the presence of an individual at or near a point without restricting its movement. The data are binary when any detections after the first are ignored (this avoids worries about the non-independence of repeated visits to a detector). 

Assuming independence among detectors, the distance-detection model applies directly as the probability of detection in a particular detector, and the overall probability of detection is the complement of the product of probabilities of non-detection in all detectors.

[^footnote4b]: The parameter vectors $\theta$ and $\theta^\prime$ differ for detection functions expressed in terms of probability ($g()$) and hazard ($\lambda()$).
<!-- Subscripts $i,s$ are included for generality, allowing individual and temporal variation in detection probability, but more often than not these do not appear in the model ($\theta_{is} = \theta$ for all $i,s$) and $p_k$ is sufficient. -->

### Poisson count proximity detector
\index{Detectors!Poisson proximity}

Hazard is the natural scale for the Poisson parameter.

### Binomial count proximity detector
\index{Detectors!Binomial proximity}

Binomial counts arise when there is a finite number of opportunities for detection within each occasion that we denote $B_s$. This commonly happens when binary proximity data are collapsed to a single occasion: the initial number of occasions is known ($B_s = S$) and places an upper limit on the count. Collapsing is often efficient. It precludes modelling parameter variation or learned responses across occasions.

Each count is binomial with size $B_s$ and probability equal to the per-occasion detection probability.

### Multi-catch trap
\index{Detectors!multi-catch trap}

A trap is a device that detains an animal until it is released, allowing only one detection of that animal per occasion. The single-detector, single-AC probability from a distance-dependent detection function (preceding section) must be modified to allow for prior capture in a different trap: traps effectively "compete" for animals. If the trap remains open for captures of further animals then the solution is a straightforward competing risk model [@be08].

The competing risk model uses the occasion- and trap-specific hazard $h_{sk}$.

### Single-catch trap
\index{Detectors!single-catch trap}

A single-catch trap can only catch one animal at a time. This entails competition 
both among traps for animals and among animals for traps. No simple likelihood is available. 
Simulation-based methods [@e04; @Efford2023] must be used for unbiased estimation of
$\theta$ and trend in density unless the time of detection has been recorded [@Distiller2015]. 

## Fixed $N$ {#fixedN}
\index{Population size $N(A)$!fixed}

The formulation of the state model as an inhomogeneous Poisson process (Chapter \@ref(Basics)) does not refer to population size $N$. The state model may also be cast as a 'conditional' or 'binomial' Poisson process' [@illian08]. For an arbitrary area $A$ the number of AC is then considered fixed rather than Poisson.

The distribution of $n$ is then binomial with size $N(A)$ and probability 
$p_c(\phi, \theta) = \int_A p_\cdot(\vec x; \theta) f(\vec x; \phi) d\vec x$, where $f(\vec x; \phi) = D(\vec x; \phi) / \int_A D(\vec x; \phi) d\vec x$.

The form conditional on $N(A)$ leads to narrower confidence intervals for density owing to the exclusion of variation in $N(A)$ among realisations of the Poisson process for AC. This makes sense when $A$ contains an isolated population with a natural boundary, but most applications do not meet this criterion.

## Confidence intervals {#confidenceintervals}
\index{Confidence intervals}

Maximizing the log likelihood leads to a straightforward estimate of the asymptotic covariance matrix $\vec V$ of the beta parameters. If $\hat \theta$ is the vector of estimates and $\vec H(\hat \theta)$ is the Hessian matrix evaluated at $\hat \theta$ then the covariance matrix is $\vec V = \vec H(\hat \theta)^{-1}$. 

> The Hessian matrix is the square matrix of second-order partial derivatives of the log likelihood. For more on asymptotic variances of MLE see @s82, @Borchers2002, @cw 1.3.2, and many statistics texts.

The sampling error of MLE is asymptotically normal, and symmetric (Wald) intervals for SECR parameters appear to work well on the link scale i.e. $\hat \theta_j \pm z_{\alpha/2} \hat \sigma_j$ is a $100(1-\alpha)\%$ interval for $\hat \theta_j$ where $-z_{\alpha/2}$ is the $\alpha/2$ quantile of the standard normal deviate ($z_{0.025} = 1.96$) and $\hat \sigma_j^2$ is the estimated variance from $\vec V$.

On back transformation to the natural ('real') scale these intervals become asymmetrical and generally have good coverage properties.

The method of profile likelihood is available (e.g., @Evans1996; `secr::confint.secr`), but it is seldom used as no problem has been shown with intervals based on asymptotic variances. Similarly, the additional computation required by parametric bootstrap methods is not warranted.

## Varying effort {#varying-effort}
\index{Varying effort}

When sampling effort varies between detectors or over time in a capture--recapture study we expect a commensurate change in the number of detections. Allowing for known variation in effort when modelling detections has these benefits:

* detection parameters are related to a consistent unit of effort (e.g., one trap set for one day)
* the fit of the detection model is improved
* trends in the estimates may be modelled without confounding.

@be08 allowed the duration of exposure to vary between sampling occasions in their competing-hazard model for
multi-catch traps. @ebm13 generalised the method to allow joint variation in effort over detectors and over time
(occasions), and considered other detector types.

We use $T_{sk}$ for the effort on occasion $s$ at detector $k$. At its simplest, $T_{sk}$ can be a binary indicator taking the values 0 (detector not used) or 1 (detector used) (when $T_{sk} = 0$, no detections are possible and $\omega_{isk} = 0$). For small, continuously varying, $T_{sk}$ we expect the number of detections to increase linearly with $T_{sk}$; saturation may occur at higher effort, depending on the detector type. Examples of possible effort variables are the number of days that each automatic camera was operated in a tiger study, or the number of rub trees sampled for DNA in each grid cell of a grizzly bear study.

Following convention in non-spatial capture--recapture [@cw] we could model $g_0$ or $\lambda_0$ on the link scale (logit or log) as a linear function of $T_{sk}$ (a time covariate if constant across detectors, a detector covariate if constant across occasions, or a time-varying detector-level covariate). However, this is suboptimal because varying effort has a linear effect only on $\lambda_0$ for Poisson count detectors, and the estimation of additional parameters is an unnecessary burden. $T_{sk}$ is like an offset in a generalised linear model: it can be included in the SECR model without estimating an additional coefficient.

The SECR models for various detectors (Table \@ref(tab:pointdetectortypes)) are expressed in terms of either the probability $p_{sk}$ or the hazard $h_{sk}$. Each of these scales differently with $T_{sk}$ as shown in Table \@ref(tab:effort). Only in the Poisson case is the expected number of detections linear on effort. 

Table: (\#tab:effort) Including effort in SECR models for various detector types. $p^\prime_{sk}(\vec x)$ and $h^\prime_{sk}(\vec x)$ replace the matching quantities in Table \@ref(tab:pointdetectortypes).

| Detector type | Adjusted probability or hazard |
|:--------------------------|:------------------------------------------|
| Multi-catch trap | $h^\prime_{sk}(\vec x) = h_{sk}(\vec x) T_{sk}$; $H^\prime_s(\vec x) = \sum_k h^\prime_{sk}(\vec x)$|
| Binary proximity | $p^\prime_{sk}(\vec x) = 1 - (1 - p_{sk}(\vec x))^{T_{sk}}$ |
| Poisson count proximity| $h^\prime_{sk}(\vec x) = h_{sk}(\vec x) T_{sk}$ |
| Binomial count proximity | see below |

For binomial count detectors we use a formulation not based directly on instantaneous hazard, as explained by @ebm13. For these detectors $T_{sk}$ (assumed integer) is taken as the size of the binomial (maximum possible detections) and $p_{sk}(\vec x)$ is unchanged.

[snowshoehare]: snowshoeharefromotisetal1978.pdf 
[otisetal]: otisetal.png
[secr-datainput.pdf]: https://www.otago.ac.nz/density/pdfs/secr-datainput.pdf
