---
editor: 
  markdown: 
    wrap: 72
---

# Likelihood-based SECR {#sec-theory}

Part II provides background on the theory of SECR that is mostly for
reference. This chapter covers general notation and theory for point detectors. @sec-areasearches describes theory for area and transect searches. @sec-specialtopics has extensions for multiple sessions, groups, effective sampling area, conditional estimation, relative density, population size, finite mixtures, hybrid mixture models, alternative parameterizations and model-based location of activity centres ('fxi'). These chapters aim to be independent of any particular
implementation, although some cross-references to **secr** creep in. 

## Notation

We use notation and terminology from @be08, with minor variations and extensions from
@ebb09, @e11 and elsewhere (@tbl-notation).

\index{Notation}

| Category   | Symbol                             | Meaning    |
|:-----------|:-----------|:----------------------------------------------|
| General    |                                    ||
|            | AC                                 | activity centre |
|            | $\mathbf x$                        | point $(x,y)$ in the plane |
| Data       |                                    ||
|            | $n$                                | number of individuals detected  |
|            | $S$                                | number of sampling occasions    |
|            | $K$                                | number of detectors             |
|            | $\omega_i$                         | spatial detection history of the $i$-th animal |
|            | $\Omega$                           | set of all detection histories $\omega_i, i = 1..n$  |
| Parameters |                                    ||
|            | $D(\mathbf x; \phi)$[^03-theory-1] | intensity at $\mathbf x$ of AC Poisson point process |
|            | $\phi$                             | parameter vector for AC point process |
|            | $\theta$                           | vector of detection parameters (minimally $(g_0, \sigma)$ or $(\lambda_0,\sigma)$)|
|            | $g_0$                              | intercept of distance-probability-of-detection function |
|            | $\lambda_0$                        | intercept of distance-hazard-of-detection function |
|            | $\sigma$                           | spatial scale parameter of distance-detection function |
| Model      |                                    ||
|            | $d_k(\mathbf x)$                   | distance of point $\mathbf x$ from detector $k$ |
|            | $\lambda(d)$                       | hazard of detection at distance $d$ (distance-hazard-of-detection function) |
|            | $g(d)$                             | probability of detection at distance $d$ (distance-probability-of-detection function) |
|            | $p_\cdot(\mathbf x; \theta)$       | probability that an individual with AC at $\mathbf x$ is detected at least once |
|            | $h_{isk}(\mathbf x; \theta)$       | hazard of detection at detector $k$ for animal $i$ on occasion $s$ |
|            | $p_{isk}(\mathbf x; \theta)$       | probability of detection corresponding to $h_{isk}(\mathbf x; \theta)$ |
|            | $p_{k}(\mathbf x; \theta)$         | $p_{isk}(\mathbf x; \theta)$ constant across individuals $i$ and occasions $s$ |
|            | $\Lambda(\phi, \theta)$            | expected number of detected individuals $n$ |
| Habitat    |                                    ||
|            | $A$                                | potential habitat ('habitat mask', 'state space') $A \subset R^2$ |
|            | $|A|$                              | area of $A$ |
|            | $N(A)$                             | number of AC in $A$ |

: Mathematical notation for SECR {#tbl-notation tbl-colwidths="[15,10,75]" .sm}

[^03-theory-1]: We use $D(\mathbf x)$ in preference to
    $\lambda(\mathbf x)$ because $\lambda$ has multiple meanings.

## Likelihood {#Likelihood}

\index{Likelihood!SECR}

Parameters of the state model ($\phi$) and the detection model
($\theta$) are estimated jointly by maximizing the logarithm of the
likelihood: 

$$
L(\phi, \theta | \Omega ) = \mathrm{Pr}(n| \phi, \theta) \; \mathrm{Pr}(\Omega | n, \phi, \theta).
$$ {#eq-L}

When density is constant across space, $\phi$ drops out of
the rightmost term, which then relates to the detection (observation)
model alone, and maximization of this component gives unbiased estimates
of $\theta$ (see [Conditional likelihood](05-theory-special-topics#sec-conditional)).

### Number of individuals {#Pr-n}

\index{Poisson process (2-D)} \index{Activity centres} If AC follow an
inhomogeneous Poisson process then $n$ has a Poisson distribution with
parameter 
$$
\Lambda(\phi, \theta) = \int_{R^2} D(\mathbf x; \phi) \, p_\cdot(\mathbf x;\theta) \, d\mathbf x, 
$$ {#eq-n} where $D(\mathbf x; \phi)$ is the density at $\mathbf x$ and
$p_\cdot(\mathbf x|\theta)$ is the overall probability of detecting an
AC at $\mathbf x$ (see @sec-pointdetectors and [@sec-areasearches]). Thus
$\mathrm{Pr}(n | \phi, \theta) = \Lambda^n \exp (-\Lambda) / n!$. 

If the population size in a defined area $A$ is considered to be [fixed](#sec-fixedN) 
rather than Poisson then the distribution of $n$ is binomial with size $N(A)$.

### Detection histories {#Pr-omega}

In general we have $$
\mathrm{Pr} (\Omega | n, \phi, \theta) = \binom {n}{n_1,...,n_C}
\prod_{i=1}^n \mathrm{Pr}( \omega_i | \omega_i>0, \phi, \theta),
$$ {#eq-CL}

where $\omega_i>0$ indicates a non-empty detection history. The
multinomial coefficient uses the frequencies $n_1,...,n_C$ of each of
the $C$ observed histories. The coefficient is a constant not involving
parameters and it can be omitted without changing the model fit
(consistent inclusion or exclusion is needed for valid likelihood-based
comparisons such as those using AIC).

We do not know the true AC locations, but they can be
integrated[^03-theory-2] out of the likelihood using an expression for
their spatial distribution, i.e. $$
\mathrm{Pr}( \omega_i | \omega_i>0, \phi, \theta) = \int_{R^2} \mathrm{Pr}( \omega_i | \omega_i>0, \theta, \mathbf x) \, f(\mathbf x | \omega_i>0, \phi, \theta) \; d\mathbf x
$$ {#eq-omegai} where $f(\mathbf x| \omega_i>0, \phi, \theta)$ is the
conditional density of an AC given that the individual was detected. The
conditional density is given by $$
f(\mathbf x| \omega_i>0, \phi, \theta) = \frac{D(\mathbf x ; \phi) p_\cdot(\mathbf x ; \theta)}{\Lambda(\phi,\theta)}.
$$ {#eq-f}

[^03-theory-2]: Integration is commonly performed by summing over many
    small cells for a finite region near the detectors, as both
    $\mathrm{Pr}(\omega_i)$ and $f(\mathbf x)$ decline to zero at greater
    distances. We state the model in terms of the real plane and defer
    discussion of the region of integration to @sec-habitat.

## Distance-dependent detection

\index{Detection model!functions}

The key idea of SECR is that the probability of detecting a particular
animal at a particular detector on one occasion can be represented as a
function of the distance between its AC and the detector. The function
should decline effectively to zero at large distances. Distances are not
observed directly, and we rely on functions of somewhat arbitrary shape.
Fortunately, the estimates are not very sensitive to the choice.
Detection functions are covered in detail in @sec-detection.
Either probability $g(d)$ or hazard $\lambda(d)$ may be modelled as a
function of distance. A halfnormal form is commonly used (e.g.,
$g(d) = g_0 \exp (-d^2/2/\sigma^2)$). The shapes of, e.g., halfnormal
$g(d)$ and halfnormal $\lambda_0(d)$ are only subtly different, but
$\lambda(d)$ is preferred because it lends itself to mathematical
manipulation and occurs more widely in the literature (often with
different notation).

The function $\lambda(d)$ may be transformed into a probability with
$g(d) = 1 - \exp[-\lambda(d)]$ and the reverse transformation is
$\lambda(d) = -\log[1-g(d)]$. The intercept parameter $g_0$ has been
replaced by $\lambda_0$; although the name $\sigma$ is retained for the
spatial scale parameter this is not exactly interchangeable between the
models.

## Detector types {#sec-pointdetectors}

\index{Detectors}
\index{Traps!multi-catch}
\index{Traps!single-catch}

The SECR data $\omega_i$ for each detected individual comprise a matrix
with dimensions $S$ (occasions) and $K$ (detectors). The matrix entries $\omega_{isk}$ may be
binary (0/1) or integer (0, 1, 2, ...). Various probability models exist
for $\omega_{isk}$. The appropriate probability model
follows in most cases directly from the type of detector device; we
therefore classify probability models according to device type.
@tbl-detectortypes matches this classification to that of @rcsg14. This
section covers passive detection at a point; [area
searches](04-theory-area-search.qmd) are considered later.

| Detector type                | Royle et al.      | Data                                               |
|:---------------------|:-----------------|:--------------------------------|
| Binary proximity             | Bernoulli^1^ | binary animal $\times$ occasion $\times$ detector  |
| Count proximity |||
| &nbsp;&nbsp;&nbsp;Poisson    | Poisson      | integer animal $\times$ occasion $\times$ detector |
| &nbsp;&nbsp;&nbsp;Binomial   | Binomial     | integer animal $\times$ occasion $\times$ detector |
| Multi-catch trap             | Multinomial  | binary animal $\times$ occasion                    |
| Single-catch trap            | ---          | binary animal $\times$ occasion, exclusive         |
| Area search                  |              | integer animal $\times$ occasion $\times$ detector |
| Transect search              |              | integer animal $\times$ occasion $\times$ detector |
| Exclusive area search^2^     |              | binary animal $\times$ occasion                    |
| Exclusive transect search^2^ |              | binary animal $\times$ occasion                    |

: Detector types based on @eb19 [Table 1] with cross references to @rcsg14 {#tbl-detectortypes tbl-colwidths="[32,18,50]" .sm}

1.  Also 'Binomial' in @rg11
2.  'Exclusive' here means that an individual can be detected at no more
    than one detector (polygon or transect) per occasion.

For each type of detector we require
$\mathrm{Pr}(\omega_{isk} | \mathbf x)$ and the overall probability of
detection $p_\cdot(\mathbf x)$. For some detector types it is more
natural to express the probability in terms of the occasion- and
trap-specific hazard
$h_{sk} = \lambda[d_k(\mathbf x); \theta^\prime]  = -\log(1-g[d_k(\mathbf x); \theta])$
than the probability
$p_{sk} (\mathbf x) = g[d_k(\mathbf x); \theta] = 1 - \exp\{-\lambda[d_k(\mathbf x); \theta^\prime]\}$[^03-theory-3].

[^03-theory-3]: The parameter vectors $\theta$ and $\theta^\prime$
    differ for detection functions expressed in terms of probability
    ($g()$) and hazard ($\lambda()$).
    <!-- Subscripts $i,s$ are included for generality, allowing individual and temporal variation in detection probability, but more often than not these do not appear in the model ($\theta_{is} = \theta$ for all $i,s$) and $p_k$ is sufficient. -->

We summarise the probability models in @tbl-pointdetectortypes, with
comments on each point detector type below.

| Detector type               | $\mathrm{Pr}(\omega_{isk} | \mathbf x)$                                                                   | $p_\cdot(\mathbf x)$                                |
|:----------------------|:------------------------|:------------------------|
| Binary proximity            | $p_{sk}(\mathbf x) ^{\omega_{isk}} [1-p_{sk}(\mathbf x)]^{(1-\omega_{isk})}$                            | $1 - \prod_s\prod_k 1 - p_{sk} (\mathbf x)$   |
| Count proximity ||
| &nbsp;&nbsp;&nbsp;Poisson    | $\{h_{sk} (\mathbf x)^{\omega_{isk}} \exp [-h_{sk}(\mathbf x)]\} / \omega_{isk}!$                       | $1 - \exp [- \sum_s \sum_k h_{sk}(\mathbf x)]$      |
| &nbsp;&nbsp;&nbsp;Binomial^1^ | $\binom{B_s}{\omega_{isk}} p_{sk}(\mathbf x)^{\omega_{isk}} [1-p_{sk}(\mathbf x)]^{(B_s-\omega_{isk})}$ | $1 - \prod_s\prod_k [1 - p_{sk} (\mathbf x)]^{B_s}$ |
| Multi-catch trap^2^         | $\{1 - \exp [-H_s(\mathbf x)]\}\frac{h_{sk}(\mathbf x)}{H_s(\mathbf x)}$                                | $1 - \exp[ -\sum_s H_s(\mathbf x)]$                 |

: Summary of point detector types (conditioning on $\theta$ omitted to
save space) {#tbl-pointdetectortypes tbl-colwidths="[20,45,35]" .sm}

1.  $B_s$ is the size of the binomial distribution, the number of
    opportunities for detection, assumed constant across detectors
2.  $H_s = \sum_k h_{sk}(\mathbf x)$ is the hazard summed over traps

<!-- ::: {.content-visible when-format="pdf"} -->

<!-- | Detector type               | $\mathrm{Pr}(\omega_{isk} | \mathbf x)$                                                                   | $p_\cdot(\mathbf x)$                                | -->
<!-- |:----------------------|:------------------------|:------------------------| -->
<!-- | Binary proximity            | $p_{sk}(\mathbf x) ^{\omega_{isk}} [1-p_{sk}(\mathbf x)]^{(1-\omega_{isk})}$                            | $1 - \prod_s\prod_k 1 - p_{sk} (\mathbf x)$         | -->
<!-- | Poisson count proximity     | $\{h_{sk} (\mathbf x)^{\omega_{isk}} \exp [-h_{sk}(\mathbf x)]\} / \omega_{isk}!$                       | $1 - \exp [- \sum_s \sum_k h_{sk}(\mathbf x)]$      | -->
<!-- | Binomial count proximity^1^ | $\binom{B_s}{\omega_{isk}} p_{sk}(\mathbf x)^{\omega_{isk}} [1-p_{sk}(\mathbf x)]^{(B_s-\omega_{isk})}$ | $1 - \prod_s\prod_k [1 - p_{sk} (\mathbf x)]^{B_s}$ | -->
<!-- | Multi-catch trap^2^         | $\{1 - \exp [-H_s(\mathbf x)]\}\frac{h_{sk}(\mathbf x)}{H_s(\mathbf x)}$                                | $1 - \exp[ -\sum_s H_s(\mathbf x)]$                 | -->

<!-- : Summary of point detector types (conditioning on $\theta$ omitted to -->
<!-- save space) {#tbl-pointdetectortypes  tbl-colwidths="[30,40,30]" .sm} -->
<!-- \ -->
<!-- 1.  $B_s$ is the size of the binomial distribution, the number of -->
<!--     opportunities for detection, assumed constant across detectors -->
<!-- 2.  $H_s = \sum_k h_{sk}(\mathbf x)$ is the hazard summed over traps -->
<!-- ::: -->

### Binary proximity detector

\index{Detectors!binary proximity}

A proximity detector records the presence of an individual at or near a
point without restricting its movement. The data are binary when any
detections after the first are ignored (this avoids worries about the
non-independence of repeated visits to a detector).

Assuming independence among detectors, the distance-detection model
applies directly as the probability of detection in a particular
detector, and the overall probability of detection is the complement of
the product of probabilities of non-detection in all detectors.

### Poisson count proximity detector

\index{Detectors!Poisson proximity}

Hazard is the natural scale for the Poisson parameter.

### Binomial count proximity detector

\index{Detectors!Binomial proximity}

Binomial counts arise when there is a known, finite number of opportunities for
detection within each occasion that we denote $B_s$. This is the result when 
binary proximity data over many occasions are collapsed to a single occasion:
the initial number of occasions is known ($B_s = S$) and places an upper
limit on the count. Collapsing is often efficient. It precludes
modelling parameter variation or learned responses across occasions.

Each count is binomial with size $B_s$ and probability equal to the
per-occasion detection probability.

### Multi-catch trap

\index{Detectors!multi-catch trap}
\index{Traps!multi-catch}

A trap is a device that detains an animal until it is released, allowing
only one detection of that animal per occasion. The single-detector,
single-AC probability from a distance-dependent detection function
(preceding section) must be modified to allow for prior capture in a
different trap: traps effectively "compete" for animals. If the trap
remains open for captures of further animals then the solution is a
straightforward competing risk model [@be08].

The competing risk model uses the occasion- and trap-specific hazard
$h_{sk}$.

### Single-catch trap {#sec-singlecatch}

\index{Detectors!single-catch trap}
\index{Traps!single-catch}

A single-catch trap can catch only one animal at a time. This entails
competition both among traps for animals and among animals for traps. No
simple likelihood is available. Simulation-based methods [@e04;
@Efford2023] must be used for unbiased estimation of $\theta$ and trend
in density unless the time of detection has been recorded
[@Distiller2015].

## Fixed $N$ {#sec-fixedN}

\index{Population size $N(A)$!fixed}

The formulation of the state model as an inhomogeneous Poisson process
(@sec-basics) does not refer to population size $N$. The state
model may also be cast as a 'conditional' or 'binomial' Poisson process'
[@illian08]. For an arbitrary area $A$ the number of AC is then
considered fixed rather than Poisson.

The distribution of $n$ is then binomial with size $N(A)$ and
probability
$p_c(\phi, \theta) = \int_A p_\cdot(\mathbf x; \theta) f(\mathbf x; \phi) d\mathbf x$,
where
$f(\mathbf x; \phi) = D(\mathbf x; \phi) / \int_A D(\mathbf x; \phi) d\mathbf x$.

The form conditional on $N(A)$ leads to narrower confidence intervals
for density owing to the exclusion of variation in $N(A)$ among
realisations of the Poisson process for AC. This makes sense when $A$
contains an isolated population with a natural boundary, but most
applications do not meet this criterion.

## Confidence intervals {#sec-confidenceintervals}

\index{Confidence intervals}

Maximizing the log likelihood leads to a straightforward estimate of the
asymptotic covariance matrix $\mathbf V$ of the beta parameters. If
$\hat \theta$ is the vector of estimates and $\mathbf H(\hat \theta)$ is
the Hessian matrix evaluated at $\hat \theta$ then an estimate of the 
covariance matrix
is $\hat {\mathbf V} = \mathbf H(\hat \theta)^{-1}$.

::: {.callout-note}
## Hessian
The Hessian matrix is the square matrix of second-order partial
derivatives of the log likelihood. For more on asymptotic variances of
MLE see @s82, @Borchers2002, @cw 1.3.2, and many statistics texts.
:::

The sampling error of MLE is asymptotically normal, and symmetric (Wald)
intervals for SECR parameters appear to work well on the link scale i.e.
$\hat \theta_j \pm z_{\alpha/2} \hat \sigma_j$ is a $100(1-\alpha)\%$
interval for $\hat \theta_j$ where $-z_{\alpha/2}$ is the $\alpha/2$
quantile of the standard normal deviate ($z_{0.025} = 1.96$) and
$\hat \sigma_j^2$ is the estimated variance from $\hat{\mathbf V}$.

On back transformation to the natural ('real') scale these intervals
become asymmetrical and generally have good coverage properties.

The method of profile likelihood is also available (e.g., @Evans1996;
`secr::confint.secr`), but it is seldom used as no problem has been
shown with intervals based on asymptotic variances. Similarly, the
additional computation required by parametric bootstrap methods is not usually 
warranted.

## Varying effort {#sec-varyingeffort}

\index{Varying effort}

When sampling effort varies between detectors or over time in a
capture--recapture study we expect a commensurate change in the number
of detections. Allowing for known variation in effort when modelling
detections has these benefits:

-   detection parameters are related to a consistent unit of effort
    (e.g., one trap set for one day)
-   the fit of the detection model is improved
-   trends in the estimates may be modelled without confounding.

@be08 allowed the duration of exposure to vary between sampling
occasions in their competing-hazard model for multi-catch traps. @ebm13
generalised the method to allow joint variation in effort over detectors
and over time (occasions), and considered other detector types.

We use $T_{sk}$ for the effort on occasion $s$ at detector $k$. At its
simplest, $T_{sk}$ can be a binary indicator taking the values 0
(detector not used) or 1 (detector used) (when $T_{sk} = 0$, no
detections are possible and $\omega_{isk} = 0$). For small, continuously
varying, $T_{sk}$ we expect the number of detections to increase
linearly with $T_{sk}$; saturation may occur at higher effort, depending
on the detector type. Examples of possible effort variables are the
number of days that each automatic camera was operated in a tiger study,
or the number of rub trees sampled for DNA in each grid cell of a
grizzly bear study.

Following convention in non-spatial capture--recapture [@cw] we could
model $g_0$ or $\lambda_0$ on the link scale (logit or log) as a linear
function of $T_{sk}$ (a time covariate if constant across detectors, a
detector covariate if constant across occasions, or a time-varying
detector-level covariate). However, this is suboptimal because varying
effort has a linear effect only on $\lambda_0$ for Poisson count
detectors, and the estimation of additional parameters is an unnecessary
burden. $T_{sk}$ is like an offset in a generalised linear model: it can
be included in the SECR model without estimating an additional
coefficient.

The SECR models for various detectors (@tbl-pointdetectortypes) are
expressed in terms of either the probability $p_{sk}$ or the hazard
$h_{sk}$. Each of these scales differently with $T_{sk}$ as shown in
@tbl-effort. Only in the Poisson case is the expected number of
detections linear on effort.

| Detector type            | Adjusted probability or hazard                                                                                   |
|:---------------------------|:-------------------------------------------|
| Multi-catch trap         | $h^\prime_{sk}(\mathbf x) = h_{sk}(\mathbf x) T_{sk}$; $H^\prime_s(\mathbf x) = \sum_k h^\prime_{sk}(\mathbf x)$ |
| Binary proximity         | $p^\prime_{sk}(\mathbf x) = 1 - (1 - p_{sk}(\mathbf x))^{T_{sk}}$                                                |
| Poisson count proximity  | $h^\prime_{sk}(\mathbf x) = h_{sk}(\mathbf x) T_{sk}$                                                            |
| Binomial count proximity | see below                                                                                                        |

: Including effort in SECR models for various detector types.
$p^\prime_{sk}(\mathbf x)$ and $h^\prime_{sk}(\mathbf x)$ replace the
matching quantities in @tbl-pointdetectortypes. {#tbl-effort  tbl-colwidths="[40,60]" .sm}

For binomial count detectors we use a formulation not based directly on
instantaneous hazard, as explained by @ebm13. For these detectors
$T_{sk}$ (assumed integer) is taken as the size of the binomial (maximum
possible detections) and $p_{sk}(\mathbf x)$ is unchanged.
