# (PART\*) Validation and applications {-} 

# Empirical validation {#Validation}

There have been few attempts to validate empirically the estimates of density from SECR: critical evaluations have relied overwhelmingly on simulation. Empirical validation requires a reliable estimate of the true density, usually from counting the individuals with activity centres in a known area. Enumeration may be by intensive observation of conspicuous diurnal species or by sampling until no new individual is found. Delineation of the relevant area is straightforward when the habitat is a natural island or fenced area. 

We describe four attempts at empirical validation of density estimates, each with a different approach. The evidence from empirical validation studies tends to be weak, owing to the wide confidence intervals and methodological constraints. None is entirely convincing, as we shall see. 

A fifth study suggests that detection parameters may vary between detector layouts. This limits the value of simulation to compare study designs.

## Brushtail possums in New Zealand

@ewcb05 live-trapped brushtail possums (*Trichosurus vulpecula*) on a coastal peninsula and compared the results to an attempted total removal by leg-hold trapping and acute poisoning. SECR estimates of density from five hollow grids were consistent with the removal estimate. 

Although broadly reassuring, the brushtail possum study had weaknesses. The live-trapping data were compromised by tag loss (documented in **secr**), the landward boundary of the removal area was somewhat arbitrary, and sampling may have been inadequate to represent density variation across the peninsula (see also the following).

## Red squirrels in the Yukon

@VanKatwyk2014 analysed data from a multi-year behavioural study of red squirrels (*Tamiasciurus hudsonicus*) in the Yukon. Squirrels were marked and followed across six study areas, each about 36-ha in area. Intensive trapping at defended food middens maintained nearly 100\% marking coverage. Capture--recapture data came from 50 cage traps operated periodically in the centre of each study area.

Calculation of 'true' density focussed on the area within the perimeter of the trapping grid. Behavioural observations of all squirrels whose territories potentially overlapped the grid (i.e. within one territory width) were scored for time spent inside the grid. The sum of these proportions is the number of 'animal equivalents' (@Boutin1984) that gives the population density when divided by the grid area.

SECR density estimates averaged only 5\% less than the 'true' density calculated by this method, and the estimates showed a strong correlation between sessions with the varying 'true' density. It is hard to fault this validation. The 'true' density was limited to the interior of each grid, whereas each SECR estimate includes data from a somewhat wider area (reversing the scenario of @Gerber2015) and sample sizes were modest. 

## Rodents in New Mexico

One major evaluation has questioned the reliability of SECR. @Gerber2015 re-analysed live-trapping data for rodents of several taxa confined to pens in New Mexico [@Parmenter2003]. Traps were arranged in either a central square grid or a star-shaped pattern, a 'trapping web'. The main study was followed by intensive trapping across the full extent of each pen to enumerate each taxon. 

SECR provided instances of both over- and under-estimation, and its performance was "sometimes underwhelming". The authors focussed on heterogeneity of detection and asymmetry of home ranges as possible explanations, although direct evidence of these effects was lacking. 

We suggest an alternative explanation. The main trap layouts did not sample the full extent of each pen, and the probability of detecting an individual in the periphery was quite low for species with small home ranges such as *Perognathus flavus* (Fig. \@ref(fig:sevilletafig)). Perfect correspondence with pen-wide exhaustive trapping is not to be expected if the density in the under-sampled peripheral zone differs from the central zone. This applies whether the difference is random or systematic. The peripheral zone ($p_\cdot(\vec x) < 0.25$) was a larger fraction of the pen for the grid ($\approx 54\%$) than for the web ($\approx 28\%$), which could explain why the grid estimates of *P. flavus* density were particularly poor [@Gerber2015 Figs. 2a, 3a)]. 

The final exhaustive trapping might be used to test the hypothesis of spatial heterogeneity, but these data are not available. Some evidence of within-pen density variation may be gleaned from density models fitted to the capture--recapture data: in 50\% of the populations a density model that included distance-to-wall as a covariate provided better fit than a null model in 50\% of cases ((likelhood ratio test $P < 0.05$; unpubl. results).

(ref:sevilletacap) *Peroganthus flavus* contours of overall 5-night detection probability $p_\cdot(\vec x)$ within a ca. 4.2-ha pen (grey shading). a. Grid, b. Trapping web. Detection parameters from first *P. flavus* population in each case.

```{r sevilletafig, echo = FALSE, message = FALSE, warning = FALSE, fig.width= 8, fig.height = 5, out.width = "80%", fig.cap="(ref:sevilletacap)"}
source("figures/sevilleta.R")
```

## Chimpanzees in Ivory Coast

@DespresEinspenner2017 applied SECR to automatic camera records of chimpanzees *Pan troglodytes* in a single group territory. Group size (27 excluding unweaned young) was known from intensive observations. The authors reported a good match between the estimated and known populations. However, $\sigma$ could not be estimated because individuals moved throughout the territory and cameras were not placed outside it (see also [Study design](#arraysize)). This required them to treat the extent of the population as known (confined within the independently determined territory boundary). The resulting analysis is in essence non-spatial, and does not validate SECR.

## Red-backed salamanders in Massachusetts

@Fleming2021 examined the effect of varying configurations of cover boards used to survey red-backed salamanders (*Plethodon cinereus*). Cover boards are artificial refuges placed on the ground. Data on salamanders found under cover boards are analysed as if they were multi-catch traps. The authors' concern was that SECR estimates of salamander density might depend on the layout and interfere with comparisons and aggregation of data across studies. Estimates of detection parameters (half-normal intercept $g_0$ and spatial scale $\sigma$) were sensitive to the extent and spacing of cover board arrays, whereas density estimates were mostly robust. Salamanders appeared more mobile (larger $\hat \sigma$) when cover boards were further apart. @Fleming2021 suggested salamanders might move directly to the next cover board even if it was further away.  

<!-- Bad choice of detectfn? Behavioural model? -->

<!-- @Twining2022 comparison live tr, camera, DNA -->


<!-- ## Simulations -->

<!-- @ebb09  -->

<!-- @Theng2022 general robustness; mechanistic simulation -->

<!-- @McLellan2023: not robust when variation in density and detection are correlated; see also @Paterson2019; @Howe2022. -->

<!-- @Royle2013; @e14 RSF -->

<!-- @Royle2015 transience -->

<!-- @Paterson2019 mountain lions simulation -->

<!-- @Dey2022 misspecified detection function -->

<!-- @Dey2023 SARE -->

<!-- @Dupont2023 ungulates simulation vs chamois (*Rupicapra rupicapra*), red deer (*Cervus elaphus*), and wild boar (*Sus scrofa*) wrt group -->

<!-- @Smith2020 simulation scenarios "caution against the casual repurposing of non-spatial capture-recapture data using SCR" -->

<!-- @Efford2019 noncircular -->

<!-- @eb19 fast design -->

<!-- @ef13 -->

<!-- @em14 -->

<!-- @Efford2024 -->

<!-- @Bischof2020 -->

<!-- @c19 -->

<!-- @Distiller2015 -->

<!-- @Dupont2019 -->
