# Datasets {#sec-datasets}

These datasets are included in **secr**. See each linked help page for details. Code for model fitting is in [secr-version4.pdf](https://www.otago.ac.nz/density/pdfs/secr-version4.pdf).

| Dataset | Description |
 |:-------------------|:---------------------------------------------------------|
 | [blackbear] \index{Black bear} | *Ursus americanus* hair snag DNA data from Tennessee |
 | [deermouse] \index{Deer mouse} |*Peromyscus maniculatus* live-trapping data of V. H. Reid published as a CAPTURE example by @obwa78 |
 | [hornedlizard]  \index{Horned lizard}| Repeated searches of a quadrat in Arizona for flat-tailed horned lizards *Phrynosoma mcallii* [@ry08] |
 | [housemouse] \index{House mouse} | *Mus musculus* live-trapping data of H. N. Coulombe published as a CAPTURE example by @obwa78 |
 | [ovenbird]   \index{Ovenbird} | Multi-year mist-netting study of ovenbirds *Seiurus aurocapilla* at a site in Maryland, USA [@de09]|
 | [ovensong]     | Acoustic detections of ovenbirds [@de09] |
 | [OVpossum] \index{Brushtail possum} | Brushtail possum *Trichosurus vulpecula* live trapping in the Orongorongo Valley, Wellington, New                        Zealand 1996--1997 [@ec04] |
 | [possum]       | Brushtail possum *Trichosurus vulpecula* live trapping at Waitarere, North Island, New Zealand April                     2002 [@ewcb05] |
 | [secrdemo]     | Simulated data 'captdata', and some fitted models |
 | [skink] \index{Oligosoma skinks} | Multi-session lizard (*Oligosoma infrapunctatum* and *O. lineoocellatum*) pitfall trapping data from                     Lake Station, Upper Buller Valley, South Island, New Zealand (Efford et al. in prep) | 
 | [stoatDNA]     | Stoat *Mustela erminea* hair tube DNA data from Matakitaki Valley, South Island, New Zealand [@ebb09] |
 
: Datasets included in **secr**  {#tbl-datasets tbl-colwidths="[20,80]" .sm}
 
[blackbear]: https://www.otago.ac.nz/density/html/blackbear.html
[deermouse]: https://www.otago.ac.nz/density/html/deermouse.html
[hornedlizard]: https://www.otago.ac.nz/density/html/hornedlizard.html
[housemouse]: https://www.otago.ac.nz/density/html/coulombe.html
[ovenbird]: https://www.otago.ac.nz/density/html/ovenbird.html
[ovensong]: https://www.otago.ac.nz/density/html/ovensong.html
[OVpossum]: https://www.otago.ac.nz/density/html/OVpossum.html
[possum]: https://www.otago.ac.nz/density/html/possum.html
[secrdemo]: https://www.otago.ac.nz/density/html/secrdemo.html
[skink]: https://www.otago.ac.nz/density/html/skink.html
[stoatDNA]: https://www.otago.ac.nz/density/html/stoatDNA.html
