# Datasets {#Datasets}

These datasets are included in **secr**. See each linked help page for details. Code for model fitting is in [secr-version4.pdf](https://www.otago.ac.nz/density/pdfs/secr-version4.pdf).

| Dataset | Description |
 |:------------|:-----------------------------------------------------------|
 | [deermouse]    |*Peromyscus maniculatus* live-trapping data of V. H. Reid published as a CAPTURE example by @obwa78 |
 | [hornedlizard] | Repeated searches of a quadrat in Arizona for flat-tailed horned lizards *Phrynosoma mcallii* [@ry08] |
 | [housemouse]   | *Mus musculus* live-trapping data of H. N. Coulombe published as a CAPTURE example by @obwa78 |
 | [ovenbird]     | Multi-year mist-netting study of ovenbirds *Seiurus aurocapilla* at a site in Maryland, USA [@de09]|
 | [ovensong]     | Acoustic detections of ovenbirds [@de09] |
 | [OVpossum]     | Brushtail possum *Trichosurus vulpecula* live trapping in the Orongorongo Valley, Wellington, New                        Zealand 1996--1997 [@ec04] |
 | [possum]       | Brushtail possum *Trichosurus vulpecula* live trapping at Waitarere, North Island, New Zealand April                     2002 [@ewcb05] |
 | [secrdemo]     | Simulated data 'captdata', and some fitted models |
 | [skink]        | Multi-session lizard (*Oligosoma infrapunctatum* and *O. lineoocellatum*) pitfall trapping data from                     Lake Station, Upper Buller Valley, South Island, New Zealand (Efford et al. in prep) | 
 | [stoatDNA]     | Stoat *Mustela erminea* hair tube DNA data from Matakitaki Valley, South Island, New Zealand [@ebb09] |
 
[deermouse]: https://www.otago.ac.nz/density/html/deermouse.html
[hornedlizard]: https://www.otago.ac.nz/density/html/hornedlizard.html
[housemouse]: https://www.otago.ac.nz/density/html/coulombe.html
[ovenbird]: https://www.otago.ac.nz/density/html/ovenbird.html
[ovensong]: https://www.otago.ac.nz/density/html/ovensong.html
[OVpossum]: https://www.otago.ac.nz/density/html/OVpossum.html
[possum]: https://www.otago.ac.nz/density/html/possum.html
[secrdemo]: https://www.otago.ac.nz/density/html/secrdemo.html
[skink]: https://www.otago.ac.nz/density/html/skink.html
[stoatDNA]: https://www.otago.ac.nz/density/html/stoatDNA.html