project:
  type: book
  output-dir: docs 
  
lightbox: auto

crossref:
  fig-prefix: Fig.
  eq-prefix: Eq.
  fig-title: Figure
  tbl-title: Table
  title-delim: ": "

nocite: |
  @Kendeigh1944

citation:
  type: book
  url: https://www.otago.ac.nz/density

metadata:
  version: "0.0.0"
  
book: 
  title: The SECR book

  subtitle: |
    |
    | A handbook of spatially explicit capture--recapture methods  
    | Version {{< meta version >}}
    |  
    |   
    | ![](images/Nickinsnow2.png){width=60%}
    
  author: 
    - name: Murray Efford
      affiliation: University of Otago, New Zealand
    
  date: today
  
  license: "CC BY-NC-ND"  
  
  reader-mode: true

  # cover-image: images/Nickinsnow3.png

  favicon: images/density6.png

  chapters:
    - index.qmd
    
    - part: "Basics"
      chapters:
      - 01-basics.qmd
      - 02-example.qmd
  
    - part: "Theory"
      chapters:
      - 03-theory.qmd
      - 04-theory-area-search.qmd
      - 05-theory-special-topics.qmd
  
    - part: "Performance"
      chapters:
      - 06-assumptions.qmd
      - 07-validation.qmd
      - 08-studydesign.qmd
  
    - part: "Practice"
      chapters:
      - 09-secr-package.qmd
      - 10-detection-model.qmd
      - 11-density-model.qmd
      - 12-habitat.qmd
      - 13-fittedmodels.qmd
      - 14-multisession.qmd
      - 15-finite-mixtures.qmd
      - 16-sex.qmd
      - 17-simulation.qmd

  appendices:
    - A01-troubleshooting.qmd
    - A02-speed.qmd
    - A03-spatial-data.qmd
    - A04-polygondetectors.qmd
    - A05-mark-resight.qmd
    - A06-noneuclidean.qmd
    - A07-telemetry.qmd
    - A08-parameterizations.qmd
    - A09-densityappendix.qmd
    - A10-trend.qmd
    - A11-expected-counts.qmd
    - A12-datasets.qmd

    - A99-references.qmd
    
  repo-url: https://github.com/MurrayEfford/SECRbook
  
  page-footer:
    center:
      - text: "The SECR book. Version {{< meta version >}}.  "
      - text: "&nbsp;&nbsp; Copyright © 2025"

bibliography: [SECRbook.bib]
# csl: journal-of-the-royal-statistical-society.csl
csl: methods-in-ecology-and-evolution.csl

github-repo: MurrayEfford/SECRbook
  
format: 
  html:
    toc: true
    toc-depth: 2
    number-sections: true
    code-link: true
    code-overflow: wrap
    html-math-method: katex
    page-layout: full
  
  pdf:
    documentclass: scrreprt
    papersize: A4
    
    toc: true
    toc-depth: 2
    include-in-header:
    - text: |
        \usepackage{booktabs}
        \usepackage{amsthm}
        \usepackage{imakeidx}
        \usepackage{amsmath}
        \usepackage{bm}
        
        \usepackage{framed}
        \usepackage{quoting}
        \quotingsetup{vskip=0pt}
        
        \makeatletter
        \def\thm@space@setup{%
          \thm@preskip=8pt plus 2pt minus 4pt
          \thm@postskip=\thm@preskip
        }
        \makeatother
        % documentclass book uses \bibname; otherwise \refname
        \renewcommand{\bibname}{References}
        % remove blank pages
        % https://tex.stackexchange.com/questions/542803/removing-blank-pages
        \let\cleardoublepage=\clearpage
        \makeindex[intoc=true]
    include-after-body:
      text: |
        \printindex

